import React from 'react';

function Explainer({ onContinue, isRoverHolder }) {
  return (
    <div className="section">
      <h2>[INSTRUCTIONS] How The Test Works</h2>
      
      <div style={{
        background: 'transparent',
        padding: '0',
        marginBottom: '32px',
        lineHeight: '1.9',
        fontSize: '0.95rem',
        color: '#ccc'
      }}>
        <h3 style={{ color: '#00ff88', marginBottom: '16px', fontSize: '1rem' }}>
          [STEP 1] Prove You Are Human
        </h3>
        <p style={{ marginBottom: '24px' }}>
          Answer a prompt question with an authentic response that demonstrates your humanity.
        </p>

        <h3 style={{ color: '#00ff88', marginBottom: '16px', fontSize: '1rem', marginTop: '24px' }}>
          [STEP 2] Identify The Humans
        </h3>
        <p style={{ marginBottom: '24px' }}>
          You will play {isRoverHolder ? '5' : '3'} rounds. In each round, you'll see two responses to the same prompt: one written by a previous human, and one generated by AI in the moment. <strong style={{ color: '#00ff88' }}>Your task is to correctly identify which response is human.</strong>
        </p>

        <h3 style={{ color: '#00ff88', marginBottom: '16px', fontSize: '1rem', marginTop: '24px' }}>
          [STEP 3] Final Judgement
        </h3>
        <p style={{ marginBottom: '24px' }}>
          Correctly identify the human response in at least 2 out of 3 rounds to pass the Rovers Reverse Turing Test. <strong style={{ color: '#00ff88' }}>Pass or fail, your wallet and credentials will be judged by The Rovers for allowlist approval.</strong> A higher score demonstrates your human authenticity and may improve your chances.
        </p>
      </div>

      <button onClick={onContinue}>
        Begin Test
      </button>
    </div>
  );
}

export default Explainer;

